defmodule ElectricCli.Flags do
  @moduledoc """
  Share default flags.
  """

  @default_flags []

  def merge_flags(command_specific \\ []) do
    @default_flags
    |> Keyword.merge(command_specific)
  end

  def default_flags do
    @default_flags
  end

  def env_options do
    [
      env: [
        short: "-e",
        long: "--env",
        value_name: "ENVIRONMENT",
        help: "The name of the app environment you want to use.",
        parser: :string,
        default: "default"
      ]
    ]
  end

  def app_flags(required? \\ true) do
    [
      app: [
        short: "-a",
        long: "--app",
        value_name: "APP",
        help: "Application identifier. Generated when you create an application in the console.",
        required: required?,
        parser: :string
      ]
    ]
  end

  # have a default of nil so that we can detect if the option has been passed or not
  def migrations_options(default \\ nil) do
    [
      migrations_dir: [
        value_name: "MIGRATIONS_DIR",
        short: "-m",
        long: "--migrations-dir",
        help:
          "Path to the directory where the migration files live. We recommend that it is named 'migrations'",
        parser: :string,
        default: default
      ]
    ]
  end

  def config_options do
    [
      root: [
        value_name: "PROJECT_DIR",
        short: "-r",
        long: "--root",
        help:
          "Path to the project directory containing the electric.json file generated by `electric init` (if not cwd)",
        parser: :string,
        default: nil
      ]
    ]
  end
end
