name: CI
on:
  push:
    branches:
      - main
  pull_request: null
  workflow_dispatch:
    inputs:
      environment:
        type: test_name
        default: tests
        required: false

env:
  MIX_ENV: test
  CACHE_VERSION: v20230113
  OTP_VERSION: "24.3"
  ELIXIR_VERSION: "1.13"

jobs:
  deps:
    name: Get all the necessary dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: ls -lah

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          elixir-version: "${{ env.ELIXIR_VERSION }}"

      - name: Try to reuse cached build
        id: cache-build-deps
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.CACHE_VERSION }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - run: mix do deps.get, deps.compile, compile


  tests:
    name: elixir tests
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          elixir-version: "${{ env.ELIXIR_VERSION }}"

      - name: Try to reuse cached build
        id: cache-build-deps
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.CACHE_VERSION }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - run: mix do deps.get, deps.compile, compile
      - run: mix test --trace


  formatting:
    name: formatting and warnings
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          elixir-version: "${{ env.ELIXIR_VERSION }}"

      - name: Try to reuse cached build
        id: cache-build-deps
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.CACHE_VERSION }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - run: mix do deps.get, deps.compile

      - name: Check formatting
        run: mix format --check-formatted

      - name: Check for warnings
        run: mix compile --force --warnings-as-errors

